server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml

